! POROSITY = unused  INPUT FILE CHANGED 


  	  ZLIM = RLIM ! HEIGHT OF ZINIT SET BY ZLIM < ZMAX
	  YPAR = AG = ! WIDTH OF PLATE SET BY AG
	  RPAR = 
	  REXIT = RJET ! LENGTH OF PLATE SET BY RJET (=REXIT)
	  Q = VJET (input volumetric flow for VJET)
C
C     SUBROUTINE TO OBTAIN INITIAL PARTICLE LOCATIONS
      SUBROUTINE INITIAL (ZLIM,AP,ASP,RMODE,ZMAX,
     &                    YPAR,YINIT,RINIT,ZINIT,HINIT)   
      DOUBLE PRECISION ZLIM,AP,ASP,ZMAX,YPAR,YINIT,RINIT,ZINIT,HINIT
      DOUBLE PRECISION rsign1,rnum1,rsign2,rnum2,rsign3,rnum3
      INTEGER  nrand,RMODE
      
      ZINIT = 2.0*ZLIM !INITIALIZE VALUE TO EXECUTE DO WHILE LOOP
      DO WHILE (ZINIT.GT.ZLIM)
C         CALL RANDOM NUMBER FOR LOCATIONS
          CALL generate_unif(rsign1,rnum1,rsign2,rnum2,rsign3,rnum3,
     &                       nrand)
          ZINIT = (rnum1)*ZMAX
          YINIT = (rnum2)*YPAR
      END DO 
      RINIT = 0.0
C     SET HINIT ACCORDING TO ROUGHNESS MODE
      IF (RMODE.EQ.0) THEN !SMOOTH-SMOOTH INTERACTION
          HINIT = ZINIT - AP
      ELSE IF ((RMODE.EQ.1).OR.(RMODE.EQ.2)) THEN !SMOOTH-ROUGH INTERACTION
          HINIT = ZINIT - AP - ASP
      ELSE IF (RMODE.EQ.3) THEN !ROUGH-ROUGH INTERACTION
          HINIT = ZINIT - AP - 0.5*(2*ASP+3**0.5*ASP) !THIRD TERM IS AVERAGE SEPARATION DISTANCE BETWEEN UNDERLYING SMOOTH SURFACES FOR OPPOSED AND COMPLIMENTARY ASPERITY PACKING
      END IF
      END SUBROUTINE INITIAL 
C
C     SUBROUTINE PARFF  
      SUBROUTINE PARFF (R,Z,Q,RPAR,ZMAX,B,VISC,VR,VZ)
	  IMPLICIT NONE
	  DOUBLE PRECISION, INTENT(IN):: R,Z,Q,RJET,ZMAX,B,VISC
      DOUBLE PRECISION, INTENT(OUT):: VR,VZ
      DOUBLE PRECISION ZR,G

      ZR = Z + B !INCLUDE SLIP LAYER FOR TANGENTIAL FLOW
      G = 12*Q*VISC/ZMAX^3
	  VR = (G/(2*VISC))*Z*(ZMAX-Z)
	  VZ = 0.0
      END SUBROUTINE PARFF
C     
      SUBROUTINE HETTRACK(X,Y,Z,Xm0,Ym0,Zm0,RZOI,RPAR,YPAR,HETMODE,
     &                    SCOV,RHET0,RHET1,RHET2,XHET,YHET,RHET)
      DIMENSION XHET(100),YHET(100),RHET(100)
      DOUBLE PRECISION X,Y,Z,Xm0,Ym0,Zm0,XHET,YHET
      DOUBLE PRECISION XP,YP,NHETREAL0,HMODEREAL,NHRINGREAL,NRINGREAL
      DOUBLE PRECISION RO,R1,RZOI,SCOV,SCOV0,RHET0,RHET1,RHET2,RHET
      DOUBLE PRECISION RRING,RRING1,ROXY,RJET
      DOUBLE PRECISION THETA,THETAP,THETAPABS,THETA1,THETA2
      DOUBLE PRECISION DTHETA,DTHETA1,DPHI,DPHI1,ARCL
      DOUBLE PRECISION PHI,PHIP,PHI1,PHI2
      DOUBLE PRECISION HM1,D
      DOUBLE PRECISION AFRACT,AF
      DOUBLE PRECISION PI
      INTEGER NHET0,HETMODE,NRING,NHETRING,NTHETA,NPHI,N,M,J
      DATA PI/3.14159265359/
      
C     CALCULATE SURFACE COVERAGE OF LARGE HETERODOMAINS
      IF (HETMODE.EQ.1) THEN
          HM1 = 0.0
      ELSEIF (HETMODE.EQ.5) THEN
          HM1 = 4.0
      END IF
      SCOV0 = SCOV*(RHET0**2)/(RHET0**2+HM1*RHET1**2)
      
C     CALCULATE APPROXIMATE NUMBER OF HETERODOMAINS REQUIRED
C     ACTUAL SURFACE COVERAGE HAS TO BE CALCULATED IN HETSAMEARC
C     AFTER ALL HETERODOMAINS ARE EXPLICITLY GENERATED
C     APPROXIMATION IS GOOD TO WITHIN 5% OR BETTER
      NHET0 = NINT(SCOV0*(RPAR*YPAR)/(PI*RHET0**2.0))
      NHETREAL0 = NHET0
C     CALCULATE NUMBER OF EVENLY SPACED LINES IN EACH DIMENSION, THE INTERSECTIONS OF WHICH ARE HETERODOMAINS
C     NX = # LINES IN RPAR DIMENSION
      NX = NINT((NHETREAL0*(RPAR/YPAR))**0.5)
C     NY = # LINES IN YPAR DIMENSION
	  NY = NINT(NX*(YPAR/RPAR))
C     CALCULATE LONGITUDINAL STEP IN RPAR 
      DTHETA =  RPAR/NX
C     CALCULATE ORTHOGONAL STEP IN YPAR 
      DPHI =  YPAR/NY
C     CALCULATE LONGITUDINAL AND ORTHOGONAL DISTANCE OF COLLOID FROM ORIGIN
      THETAP = X-Xm0 ! THETAP IS COLLOID LONGITUDINAL DISTANCE FROM AXIS
	  PHIP = Y-Ym0 ! PHIP IS COLLOID ORTHOGONAL DISTANCE FROM AXIS
C     FIND CLOSEST NX TO PARTICLE PROJECTION
C     SINCE THE RING NUMBER 1 IS CLOSEST TO AXIS  
      NTHETA = NINT(THETAP/DTHETA)
	  NPHI = NINT(PHIP/DPHI)
   	  D = (2**0.5)/2
C
C     FIND CLOSEST HETERODOMAIN
      THETA = NTHETA*DTHETA
	  PHI = NPHI*DPHI
      DO J=1,HETMODE
          IF (J.EQ.1) THEN !RECOGNIZE LARGE HETERODOMAIN NOT AT AXIS
              XHET(J) = THETA+Xm0
              YHET(J) = PHI+Ym0
              RHET(J) = RHET0
          ELSE !RECOGNIZE MEDIUM AND/OR SMALL HETERODOMAINS AROUND LARGE HETERODOMAIN
			  IF (J.EQ.2) THEN 
				  THETA1 = -D*(1.0/3.0*DTHETA) 
				  PHI1 = -D*(1.0/3.0*DPHI)
			  END IF
			  IF (J.EQ.3) THEN 
				  THETA1 = D*(1.0/3.0*DTHETA)  
				  PHI1 = D*(1.0/3.0*DPHI)
			  END IF
			  IF (J.EQ.4) THEN 
				  THETA1 = D*(1.0/3.0*DTHETA)  
				  PHI1 = -D*(1.0/3.0*DPHI) 
			  END IF
			  IF (J.EQ.5) THEN 
				  THETA1 = -D*(1.0/3.0*DTHETA)  
				  PHI1 = D*(1.0/3.0*DPHI)
			  END IF                                   
              XHET(J) = THETA1+THETA+Xm0
			  YHET(J) = PHI1+PHI+Ym0
			  RHET(J) = RHET1
          END IF                      
      END DO
      END SUBROUTINE HETTRACK
